/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.InvoiceController;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author leont
 */
public class InvoiceDisplayPanel extends javax.swing.JPanel {
    
    InvoiceController invoiceController;

    /**
     * Creates new form InvoiceDisplayPanel
     */
    public InvoiceDisplayPanel(InvoiceController invoiceController) {
        this.invoiceController = invoiceController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        customerLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        customerLbl2 = new javax.swing.JLabel();
        dateLbl2 = new javax.swing.JLabel();
        totalPriceLbl = new javax.swing.JLabel();
        nextInvoiceBtn = new javax.swing.JButton();
        prevInvoiceBtn = new javax.swing.JButton();
        totalAmountLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1600, 800));
        setLayout(new java.awt.GridBagLayout());

        itemTable.setBackground(new java.awt.Color(255, 255, 255));
        itemTable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        itemTable.setForeground(new java.awt.Color(0, 0, 0));
        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Price per item", "Amount", "Total price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableColumnModel tcm = itemTable.getColumnModel();
        tcm.getColumn(0).setPreferredWidth(50);
        tcm.getColumn(1).setPreferredWidth(500);
        tcm.getColumn(2).setPreferredWidth(50);
        tcm.getColumn(3).setPreferredWidth(50);
        tcm.getColumn(4).setPreferredWidth(50);
        itemTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        itemTable.setRowHeight(30);
        itemTable.setRowSelectionAllowed(false);
        itemTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(itemTable);
        if (itemTable.getColumnModel().getColumnCount() > 0) {
            itemTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        customerLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        customerLbl.setText("Customer: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(21, 23, 0, 0);
        add(customerLbl, gridBagConstraints);

        dateLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dateLbl.setText("Date: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(21, 397, 0, 0);
        add(dateLbl, gridBagConstraints);

        customerLbl2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        customerLbl2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customerLbl2.setText("jLabel1");
        customerLbl2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        customerLbl2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        customerLbl2.setPreferredSize(new java.awt.Dimension(500, 22));
        customerLbl2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 0, 0, 0);
        add(customerLbl2, gridBagConstraints);

        dateLbl2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dateLbl2.setText("jLabel2");
        dateLbl2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dateLbl2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 0, 0, 23);
        add(dateLbl2, gridBagConstraints);

        totalPriceLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        totalPriceLbl.setText("Total price: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(14, 36, 19, 48);
        add(totalPriceLbl, gridBagConstraints);

        nextInvoiceBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nextInvoiceBtn.setText("Next invoice ");
        nextInvoiceBtn.setToolTipText("");
        nextInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextInvoiceBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        add(nextInvoiceBtn, gridBagConstraints);

        prevInvoiceBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        prevInvoiceBtn.setText("Previous invoice");
        prevInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevInvoiceBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        add(prevInvoiceBtn, gridBagConstraints);

        totalAmountLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        totalAmountLbl.setText("Total amount: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(14, 36, 19, 48);
        add(totalAmountLbl, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void prevInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevInvoiceBtnMouseClicked
        this.invoiceController.prevInvoice(this);
    }//GEN-LAST:event_prevInvoiceBtnMouseClicked

    private void nextInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextInvoiceBtnMouseClicked
        this.invoiceController.nextInvoice(this);
    }//GEN-LAST:event_nextInvoiceBtnMouseClicked

    public void setCustomerInfo(String customerInfo) {
        this.customerLbl2.setText(customerInfo);
    }

    public void setDate(String date) {
        this.dateLbl2.setText(date);
    }
    public void clearTable(){
        DefaultTableModel dtm = (DefaultTableModel) this.itemTable.getModel();
        dtm.setRowCount(0);   
    }
    
    public void insertRow(String[] columns) {
        DefaultTableModel model = (DefaultTableModel)this.itemTable.getModel();
        model.addRow(columns);
    }
    
    public void displayTotalAmount(int totalAmount) {
        this.totalAmountLbl.setText("Total amount: " + totalAmount);
    }
    
    public void displayTotalPrice(String totalPrice){
        this.totalPriceLbl.setText("Total price: " + totalPrice);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerLbl;
    private javax.swing.JLabel customerLbl2;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel dateLbl2;
    private javax.swing.JTable itemTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextInvoiceBtn;
    private javax.swing.JButton prevInvoiceBtn;
    private javax.swing.JLabel totalAmountLbl;
    private javax.swing.JLabel totalPriceLbl;
    // End of variables declaration//GEN-END:variables

}
