/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author leont
 */
public class ItemCreationPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemCreationPanel
     */
    public ItemCreationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemDescTxt = new javax.swing.JTextArea();
        itemNameLbl = new javax.swing.JLabel();
        itemDescLbl = new javax.swing.JLabel();
        itemPriceLbl = new javax.swing.JLabel();
        itemNameTxt = new javax.swing.JTextField();
        itemPriceTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 204, 255));

        itemDescTxt.setColumns(20);
        itemDescTxt.setLineWrap(true);
        itemDescTxt.setRows(5);
        itemDescTxt.setWrapStyleWord(true);
        jScrollPane1.setViewportView(itemDescTxt);

        itemNameLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        itemNameLbl.setText("Name: ");

        itemDescLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        itemDescLbl.setText("Description: ");
        itemDescLbl.setToolTipText("");

        itemPriceLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        itemPriceLbl.setText("Price: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemPriceLbl)
                    .addComponent(itemDescLbl)
                    .addComponent(itemNameLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(itemNameTxt)
                    .addComponent(itemPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameLbl)
                    .addComponent(itemNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemDescLbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemPriceLbl)
                    .addComponent(itemPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public String[] getItemInfo(){
        String[] info = {this.itemNameTxt.getText(), this.itemDescTxt.getText(),
                         this.itemPriceTxt.getText()};
        return info;
    }
    
    void setItemInfo(String[] itemInfo) {
        this.itemNameTxt.setText(itemInfo[0]);
        this.itemDescTxt.setText(itemInfo[1]);
        this.itemPriceTxt.setText(itemInfo[2]);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemDescLbl;
    private javax.swing.JTextArea itemDescTxt;
    private javax.swing.JLabel itemNameLbl;
    private javax.swing.JTextField itemNameTxt;
    private javax.swing.JLabel itemPriceLbl;
    private javax.swing.JTextField itemPriceTxt;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
