/*
 * To allow users to select a date we are using the library jcalendar-1.4 taken from:
 * https://toedter.com/jcalendar/ Documentation: 
 * https://www.ssec.wisc.edu/mcidas/software/v/javadoc/1.4/edu/wisc/ssec/mcidasv/data/dateChooser/JCalendar.html
 */
package view;
import controller.CustomerController;
import controller.InvoiceController;
import controller.ItemController;
import exceptions.MissingDataException;
import exceptions.NoItemsAddedException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;
/**
 *
 * @author leont
 */
public class MainWindow extends javax.swing.JFrame {
    private final CustomerController customersController = new CustomerController();
    private final ItemController itemsController = new ItemController();
    private final InvoiceController invoiceController = new InvoiceController(customersController, itemsController);
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        customerLbl1 = new javax.swing.JLabel();
        customersBox = new javax.swing.JComboBox<>();
        itemEditBtn = new javax.swing.JButton();
        editCustomerBtn = new javax.swing.JButton();
        addCustomerBtn1 = new javax.swing.JButton();
        dateLbl = new javax.swing.JLabel();
        itemLbl = new javax.swing.JLabel();
        itemsBox = new javax.swing.JComboBox<>();
        totalPriceLbl = new javax.swing.JLabel();
        submitInvoiceBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        addedItemsList = new javax.swing.JList<>();
        totalAmountLbl = new javax.swing.JLabel();
        addItemBtn = new javax.swing.JButton();
        addItemInvoiceBtn = new javax.swing.JButton();
        removeItemInvoiceBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        amountText = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        amountLbl = new javax.swing.JLabel();
        viewInvoicesBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invoicer");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("Invoicer"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        customerLbl1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customerLbl1.setText("Customer: ");
        customerLbl1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 0);
        jPanel1.add(customerLbl1, gridBagConstraints);

        customersBox.setBackground(new java.awt.Color(0, 153, 255));
        customersBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        customersBox.setModel(this.customersController.getCustomers());
        customersBox.setMaximumSize(new java.awt.Dimension(33, 26));
        customersBox.setPrototypeDisplayValue("Firstname Middlename Lastname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel1.add(customersBox, gridBagConstraints);

        itemEditBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        itemEditBtn.setText("Edit selected Item");
        itemEditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemEditBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(itemEditBtn, gridBagConstraints);

        editCustomerBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        editCustomerBtn.setText("Edit selected customer");
        editCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCustomerBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(editCustomerBtn, gridBagConstraints);

        addCustomerBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addCustomerBtn1.setText("Add new customer");
        addCustomerBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBtn1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(addCustomerBtn1, gridBagConstraints);

        dateLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dateLbl.setText("Date: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 0);
        jPanel1.add(dateLbl, gridBagConstraints);

        itemLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        itemLbl.setText("Item: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 0);
        jPanel1.add(itemLbl, gridBagConstraints);

        itemsBox.setBackground(new java.awt.Color(0, 153, 255));
        itemsBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        itemsBox.setModel(this.itemsController.getItems());
        itemsBox.setPrototypeDisplayValue("Firstname Middlename Lastname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel1.add(itemsBox, gridBagConstraints);

        totalPriceLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalPriceLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalPriceLbl.setText("Total price: 0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        jPanel1.add(totalPriceLbl, gridBagConstraints);

        submitInvoiceBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submitInvoiceBtn.setText("Submit invoice");
        submitInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitInvoiceBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(submitInvoiceBtn, gridBagConstraints);

        addedItemsList.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addedItemsList.setModel(this.invoiceController.getListedItems());
        addedItemsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(addedItemsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 208;
        gridBagConstraints.ipady = 141;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane2, gridBagConstraints);

        totalAmountLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalAmountLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalAmountLbl.setText("Total amount: 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        jPanel1.add(totalAmountLbl, gridBagConstraints);

        addItemBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addItemBtn.setText("Add new item");
        addItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addItemBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(addItemBtn, gridBagConstraints);

        addItemInvoiceBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addItemInvoiceBtn.setText("Add item to invoice");
        addItemInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addItemInvoiceBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(addItemInvoiceBtn, gridBagConstraints);

        removeItemInvoiceBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        removeItemInvoiceBtn.setText("Remove item from invoice");
        removeItemInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeItemInvoiceBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(removeItemInvoiceBtn, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMinimumSize(new java.awt.Dimension(2, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(jSeparator1, gridBagConstraints);

        amountText.setBackground(java.awt.Color.white);
        amountText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        amountText.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(amountText, gridBagConstraints);

        jDateChooser1.setBackground(new java.awt.Color(153, 204, 255));
        jDateChooser1.setForeground(new java.awt.Color(0, 153, 255));
        jDateChooser1.setDate(new Date());
        ((JTextComponent)jDateChooser1.getDateEditor()).setEditable(false);
        jDateChooser1.setDateFormatString("dd.MM.yyyy");
        jDateChooser1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jDateChooser1.setPreferredSize(new java.awt.Dimension(56, 34));
        jDateChooser1.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 5);
        jPanel1.add(jDateChooser1, gridBagConstraints);

        amountLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        amountLbl.setText("Amount: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(amountLbl, gridBagConstraints);

        viewInvoicesBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewInvoicesBtn.setText("View invoices");
        viewInvoicesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewInvoicesBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 25;
        jPanel1.add(viewInvoicesBtn, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemInvoiceBtnMouseClicked
        int itemIndex = this.itemsBox.getSelectedIndex();
        // TODO no item selected
        try{
            int amount = Integer.parseInt(this.amountText.getText());
            this.invoiceController.addItemToList(itemIndex, amount, this.totalAmountLbl, this.totalPriceLbl);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Not valid amount!", "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "No item to add! Create a new item using the"
                                          + " \"Add new item\" button", "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
        catch (MissingDataException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_addItemInvoiceBtnMouseClicked

    private void addCustomerBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtn1MouseClicked
        try{
            CustomerCreationPanel panel = new CustomerCreationPanel();
            String[] options = {"Submit", "Cancel"};
            int result = JOptionPane.showOptionDialog(jPanel1, panel, "Enter customer information", 
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
            String[] info = panel.getCustomerInfo();
            this.customersController.addCustomer(result, info);   
        }
        catch (MissingDataException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addCustomerBtn1MouseClicked

    private void editCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerBtnMouseClicked
        try {
            int customerIndex = this.customersBox.getSelectedIndex();
            CustomerCreationPanel panel = new CustomerCreationPanel();
            String[] customerInfo = this.customersController.getCustomerInfo(customerIndex);
            panel.setCustomerInfo(customerInfo);
            String[] options = {"Delete", "Submit", "Cancel"};
            int result = JOptionPane.showOptionDialog(jPanel1, panel, "Enter customer information", 
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
            String[] newCustomerInfo = panel.getCustomerInfo();
            this.customersController.editCustomer(result, customerIndex, newCustomerInfo);
            this.customersBox.repaint();
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "No customer selected! Add a customer using the "
                                          + "\"Add new customer\" button", "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
        catch (MissingDataException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editCustomerBtnMouseClicked

    private void addItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemBtnMouseClicked
        try {
            ItemCreationPanel panel = new ItemCreationPanel();
            String[] options = {"Submit", "Cancel"};
            int result = JOptionPane.showOptionDialog(jPanel1, panel, "Enter item information", 
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
            String[] info = panel.getItemInfo();
            this.itemsController.addItem(result, info); 
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Not valid price", "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
        catch (MissingDataException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addItemBtnMouseClicked

    private void itemEditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemEditBtnMouseClicked
        try {
            ItemCreationPanel panel = new ItemCreationPanel();
            int itemIndex = this.itemsBox.getSelectedIndex();
            String[] itemInfo = this.itemsController.getItemInfo(itemIndex);
            panel.setItemInfo(itemInfo);
            String[] options = {"Delete", "Submit", "Cancel"};
            int result = JOptionPane.showOptionDialog(jPanel1, panel, "Enter customer information", 
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
            String[] newItemInfo = panel.getItemInfo();
            this.itemsController.editItem(result, itemIndex, newItemInfo);
            this.itemsBox.repaint();
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "No item selected! Add an item using the "
                                          + "\"Add new item\" button", "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Not valid price", "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemEditBtnMouseClicked

    private void removeItemInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeItemInvoiceBtnMouseClicked
        try {
            this.invoiceController.removeItemFromList(this.addedItemsList.getSelectedIndex(),
                                                      this.totalAmountLbl, this.totalPriceLbl);
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "No item selected in the list!", "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeItemInvoiceBtnMouseClicked

    private void submitInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitInvoiceBtnMouseClicked
        try {
            String date = ((JTextComponent)this.jDateChooser1.getDateEditor()).getText();
            InvoiceDisplayPanel invoicePanel = new InvoiceDisplayPanel(this.invoiceController);
            this.invoiceController.createInvoice(date, this.customersBox.getSelectedIndex(),invoicePanel);
            this.totalAmountLbl.setText("Total amount: 0");
            this.totalPriceLbl.setText("Total price: 0.00");
            this.displayInvoiceViewer(invoicePanel);
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Something is missing! Make sure you added a customer "
                                          + "and items to the invoice.", "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
        catch(NoItemsAddedException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Oops, something's wrong...",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitInvoiceBtnMouseClicked

    private void viewInvoicesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInvoicesBtnMouseClicked
        InvoiceDisplayPanel invoicePanel = new InvoiceDisplayPanel(this.invoiceController);       
        if (this.invoiceController.newestInvoice(invoicePanel)){
            this.displayInvoiceViewer(invoicePanel);
        }
    }//GEN-LAST:event_viewInvoicesBtnMouseClicked
    
    private void displayInvoiceViewer(InvoiceDisplayPanel invoicePanel){
        JFrame frame = new JFrame ("Invoice viewer");
        frame.setDefaultCloseOperation (JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(invoicePanel);
        frame.pack();
        frame.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBtn1;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton addItemInvoiceBtn;
    private javax.swing.JList<String> addedItemsList;
    private javax.swing.JLabel amountLbl;
    private javax.swing.JTextField amountText;
    private javax.swing.JLabel customerLbl1;
    private javax.swing.JComboBox<String> customersBox;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JButton editCustomerBtn;
    private javax.swing.JButton itemEditBtn;
    private javax.swing.JLabel itemLbl;
    private javax.swing.JComboBox<String> itemsBox;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton removeItemInvoiceBtn;
    private javax.swing.JButton submitInvoiceBtn;
    private javax.swing.JLabel totalAmountLbl;
    private javax.swing.JLabel totalPriceLbl;
    private javax.swing.JButton viewInvoicesBtn;
    // End of variables declaration//GEN-END:variables
}
